version: "3.8"
services:

  app:
    build:
      args:
        user: system
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: project
    container_name: project-app
    restart: unless-stopped
    working_dir: /var/www
    ports:
      - 5173:5173
    volumes:
      - ./:/var/www
    networks:
      - project

  db:
    image: mysql:8.0
    container_name: project-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-password}
      MYSQL_DATABASE: ${DB_DATABASE:-project-db}
      MYSQL_USER: ${DB_USERNAME:-projectsys}
      MYSQL_PASSWORD: ${DB_PASSWORD:-password}
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    networks:
      - project

  nginx:
    image: nginx:1.21.6-alpine
    container_name: project-nginx
    restart: unless-stopped
    volumes:
      - ./docker-compose/nginx/project.conf:/etc/nginx/conf.d/default.conf
      - ./:/var/www
    ports:
      - 8000:80
    networks:
      - project

networks:
  project:
    driver: bridge